/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LeadListsRouteImport } from './routes/lead-lists'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HotLeadsRouteImport } from './routes/hot-leads'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadListsRoute = LeadListsRouteImport.update({
  id: '/lead-lists',
  path: '/lead-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HotLeadsRoute = HotLeadsRouteImport.update({
  id: '/hot-leads',
  path: '/hot-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/automations': typeof AutomationsRoute
  '/calls': typeof CallsRoute
  '/campaigns': typeof CampaignsRoute
  '/hot-leads': typeof HotLeadsRoute
  '/inbox': typeof InboxRoute
  '/lead-lists': typeof LeadListsRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/automations': typeof AutomationsRoute
  '/calls': typeof CallsRoute
  '/campaigns': typeof CampaignsRoute
  '/hot-leads': typeof HotLeadsRoute
  '/inbox': typeof InboxRoute
  '/lead-lists': typeof LeadListsRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/automations': typeof AutomationsRoute
  '/calls': typeof CallsRoute
  '/campaigns': typeof CampaignsRoute
  '/hot-leads': typeof HotLeadsRoute
  '/inbox': typeof InboxRoute
  '/lead-lists': typeof LeadListsRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/analytics'
    | '/automations'
    | '/calls'
    | '/campaigns'
    | '/hot-leads'
    | '/inbox'
    | '/lead-lists'
    | '/leads'
    | '/meetings'
    | '/proposals'
    | '/settings'
    | '/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/analytics'
    | '/automations'
    | '/calls'
    | '/campaigns'
    | '/hot-leads'
    | '/inbox'
    | '/lead-lists'
    | '/leads'
    | '/meetings'
    | '/proposals'
    | '/settings'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/analytics'
    | '/automations'
    | '/calls'
    | '/campaigns'
    | '/hot-leads'
    | '/inbox'
    | '/lead-lists'
    | '/leads'
    | '/meetings'
    | '/proposals'
    | '/settings'
    | '/workspaces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomationsRoute: typeof AutomationsRoute
  CallsRoute: typeof CallsRoute
  CampaignsRoute: typeof CampaignsRoute
  HotLeadsRoute: typeof HotLeadsRoute
  InboxRoute: typeof InboxRoute
  LeadListsRoute: typeof LeadListsRoute
  LeadsRoute: typeof LeadsRoute
  MeetingsRoute: typeof MeetingsRoute
  ProposalsRoute: typeof ProposalsRoute
  SettingsRoute: typeof SettingsRoute
  WorkspacesRoute: typeof WorkspacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-lists': {
      id: '/lead-lists'
      path: '/lead-lists'
      fullPath: '/lead-lists'
      preLoaderRoute: typeof LeadListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-leads': {
      id: '/hot-leads'
      path: '/hot-leads'
      fullPath: '/hot-leads'
      preLoaderRoute: typeof HotLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomationsRoute: AutomationsRoute,
  CallsRoute: CallsRoute,
  CampaignsRoute: CampaignsRoute,
  HotLeadsRoute: HotLeadsRoute,
  InboxRoute: InboxRoute,
  LeadListsRoute: LeadListsRoute,
  LeadsRoute: LeadsRoute,
  MeetingsRoute: MeetingsRoute,
  ProposalsRoute: ProposalsRoute,
  SettingsRoute: SettingsRoute,
  WorkspacesRoute: WorkspacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
